title: Deven Bansod
logo: /images/devenbansod.jpg
description: Grad Student at Georgia Institute of Technology.
google_analytics: UA-133375103-1
theme: jekyll-theme-minimal
show_downloads: false
github.is_project_page: false
logo_desc: Cairns, QLD, Australia (June 2018)
